package org.gimnechiske.jRM.core;

import java.util.ArrayList;

import org.gimnechiske.jRM.*;
import org.gimnechiske.jRM.skillcategories.*;

public class Library {
	private ArrayList<SkillCategory> skillCats = new ArrayList<>();
	public Library() {
		Ability t;
		t = new ArmorHeavy();
		skillCats.add((SkillCategory) t);
		t = new ArmorLight();
		skillCats.add((SkillCategory) t);
		t = new ArmorMedium();
		skillCats.add((SkillCategory) t);
		t = new ArtisticActive();
		skillCats.add((SkillCategory) t);
		t = new ArtisticPassive();
		skillCats.add((SkillCategory) t);
		t = new AthleticBrawn();
		skillCats.add((SkillCategory) t);
		t = new AthleticEndurance();
		skillCats.add((SkillCategory) t);
		t = new AthleticGymnastics();
		skillCats.add((SkillCategory) t);
		t = new AwarenessPerception();
		skillCats.add((SkillCategory) t);
		t = new AwarenessSearching();
		skillCats.add((SkillCategory) t);
		t = new AwarenessSenses();
		skillCats.add((SkillCategory) t);
		t = new BodyDevelopment();
		skillCats.add((SkillCategory) t);
		t = new CombatManeuvers();
		skillCats.add((SkillCategory) t);
		t = new Communications();
		skillCats.add((SkillCategory) t);
		t = new Crafts();
		skillCats.add((SkillCategory) t);
		t = new DirectedSpells();
		skillCats.add((SkillCategory) t);
		t = new Influence();
		skillCats.add((SkillCategory) t);
		t = new LoreAcademic();
		skillCats.add((SkillCategory) t);
		t = new LoreGeneral();
		skillCats.add((SkillCategory) t);
		t = new LoreMagical();
		skillCats.add((SkillCategory) t);
		t = new LoreObscure();
		skillCats.add((SkillCategory) t);
		t = new LoreTechnical();
		skillCats.add((SkillCategory) t);
		t = new MartialArtsCombatManeuvers();
		skillCats.add((SkillCategory) t);
		t = new MartialArtsStriking();
		skillCats.add((SkillCategory) t);
		t = new MartialArtsSweeps();
		skillCats.add((SkillCategory) t);
		t = new MindPointDevelopment();
		skillCats.add((SkillCategory) t);
		t = new OutdoorAnimal();
		skillCats.add((SkillCategory) t);
		t = new OutdoorEnvironmental();
		skillCats.add((SkillCategory) t);
		t = new PowerAwareness();
		skillCats.add((SkillCategory) t);
		t = new PowerManipulation();
		skillCats.add((SkillCategory) t);
		t = new PowerPointDevelopment();
		skillCats.add((SkillCategory) t);
		t = new PsychicElectrokinesis();
		skillCats.add((SkillCategory) t);
		t = new PsychicHealing();
		skillCats.add((SkillCategory) t);
		t = new PsychicMetaPsi();
		skillCats.add((SkillCategory) t);
		t = new PsychicMindOverMatter();
		skillCats.add((SkillCategory) t);
		t = new PsychicPhotokinesis();
		skillCats.add((SkillCategory) t);
		t = new PsychicPsychokinesis();
		skillCats.add((SkillCategory) t);
		t = new PsychicRadiokinesis();
		skillCats.add((SkillCategory) t);
		t = new PsychicTelepathy();
		skillCats.add((SkillCategory) t);
		t = new PsychicThermokinesis();
		skillCats.add((SkillCategory) t);
		t = new ScienceAnalyticBasic();
		skillCats.add((SkillCategory) t);
		t = new ScienceAnalyticEngineering();
		skillCats.add((SkillCategory) t);
		t = new ScienceAnalyticMedical();
		skillCats.add((SkillCategory) t);
		t = new ScienceAnalyticSpecialized();
		skillCats.add((SkillCategory) t);
		t = new ScienceAnalyticTechnical();
		skillCats.add((SkillCategory) t);
		t = new SelfControl();
		skillCats.add((SkillCategory) t);
		t = new SpecialAttacks();
		skillCats.add((SkillCategory) t);
		t = new SpecialDefenses();
		skillCats.add((SkillCategory) t);
		t = new SubterfugeAttack();
		skillCats.add((SkillCategory) t);
		t = new SubterfugeMechanics();
		skillCats.add((SkillCategory) t);
		t = new SubterfugeStealth();
		skillCats.add((SkillCategory) t);
		t = new TechnicalTradeGeneral();
		skillCats.add((SkillCategory) t);
		t = new TechnicalTradeGunnery();
		skillCats.add((SkillCategory) t);
		t = new TechnicalTradeProfessional();
		skillCats.add((SkillCategory) t);
		t = new TechnicalTradeVehicles();
		skillCats.add((SkillCategory) t);
		t = new TechnicalTradeVocational();
		skillCats.add((SkillCategory) t);
		t = new Urban();
		skillCats.add((SkillCategory) t);
		t = new Weapon1HConcussion();
		skillCats.add((SkillCategory) t);
		t = new Weapon1HEdged();
		skillCats.add((SkillCategory) t);
		t = new Weapon1HEnergy();
		skillCats.add((SkillCategory) t);
		t = new Weapon1HFirearms();
		skillCats.add((SkillCategory) t);
		t = new Weapon2Handed();
		skillCats.add((SkillCategory) t);
		t = new Weapon2HEnergy();
		skillCats.add((SkillCategory) t);
		t = new Weapon2HFirearms();
		skillCats.add((SkillCategory) t);
		t = new WeaponMissile();
		skillCats.add((SkillCategory) t);
		t = new WeaponMissileArtillery();
		skillCats.add((SkillCategory) t);
		t = new WeaponPoleArms();
		skillCats.add((SkillCategory) t);
		t = new WeaponSupport();
		skillCats.add((SkillCategory) t);
		t = new WeaponThrown();
		skillCats.add((SkillCategory) t);
	}
	public ArrayList<SkillCategory> getSkillCategories() {
		return skillCats;
	}
}
